[FEAT] added a fixed menu bar and some scaling adaptation
basov-tech/landing-page pull request #6
Opened 2023-08-23 07:10 UTC by vlad-lisnenko

2023-08-23 07:50 UTC, scratchw0w approved these changes

2023-08-23 07:50 UTC, scratchw0w commented on css/style.css
> +  transition: background-color 0.3s ease-in-out; /* Добавляем анимацию смены фона */
no need in comment

2023-08-23 07:50 UTC, scratchw0w commented on index.html
>        <h2 class="title-for-container-right">V</h2>
add spacing

2023-08-23 07:53 UTC, merged

2023-08-24 20:36 UTC, scratchw0w requested changes
Please resolve comments

2023-08-24 20:36 UTC, scratchw0w commented on css/style.css
please remove body{} and .page comments, I guess we don't need it anymore.

Also could you remove script and other staff linked with smart scrolling.

2023-08-24 20:36 UTC, scratchw0w commented on css/style.css
> +.scrolling-container {
Don't we need /* Main Container */ comment in here?

2023-08-24 20:36 UTC, scratchw0w commented on css/style.css
> +  /* max-width: 40%; */
please remove unnecessary comment

2023-08-24 20:36 UTC, scratchw0w commented on js/script.js
> +  if (scrollY > 100) {
please move magic number to constant

2023-08-24 20:36 UTC, scratchw0w commented on js/script.js
> +    scrollingContainer.classList.add('black-bg');
use const var black-bg instead

2023-08-24 20:36 UTC, scratchw0w commented on js/script.js
> +    scrollingContainer.classList.remove('black-bg');
and here

2023-08-24 20:36 UTC, scratchw0w commented on index.html
> +          <img class="icon" src="src/computer-logo-border.png" alt="Icon" />
I guess there should be alt = Error message, for ex. "Icon loading failed, please try again"

2023-08-24 20:36 UTC, scratchw0w commented on index.html
> +        <img class="vision right" src="src/vision_2.jpg" alt="Second Image" />
same for alt, error msg

please make it in all alts

2023-08-24 20:36 UTC, scratchw0w commented on index.html
>      <!-- <div class="page"> -->
may be removed

2023-08-24 20:36 UTC, scratchw0w commented on index.html
>      <!-- <div class="page"> -->
may be removed

2023-08-24 20:36 UTC, scratchw0w commented on index.html
>      <!-- <div class="page"> -->
may be removed

2023-08-24 20:36 UTC, scratchw0w commented on index.html
>      <!-- <div class="page"> -->
may be removed

2023-08-24 20:36 UTC, scratchw0w commented on index.html
>      <!-- Footer -->
may be removed

2023-08-24 20:36 UTC, scratchw0w commented on index.html
>      <!-- todo: make footer visible through scrolling -->
may be removed and script below too

2023-08-24 20:52 UTC, vlad-lisnenko commented on css/style.css
> +.scrolling-container {
is this the main container ? its scrollling-container